/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICAFGameManager,
  ICAFGameManagerInterface,
} from "../../../../contracts/core/interfaces/ICAFGameManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "transferToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICAFGameManager__factory {
  static readonly abi = _abi;
  static createInterface(): ICAFGameManagerInterface {
    return new Interface(_abi) as ICAFGameManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICAFGameManager {
    return new Contract(address, _abi, runner) as unknown as ICAFGameManager;
  }
}
