/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICAFItems,
  ICAFItemsInterface,
} from "../../../../contracts/core/interfaces/ICAFItems";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
    ],
    name: "remove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICAFItems__factory {
  static readonly abi = _abi;
  static createInterface(): ICAFItemsInterface {
    return new Interface(_abi) as ICAFItemsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICAFItems {
    return new Contract(address, _abi, runner) as unknown as ICAFItems;
  }
}
