/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICAFCompanyItems__factory } from "./ICAFCompanyItems__factory";
export { ICAFContractRegistry__factory } from "./ICAFContractRegistry__factory";
export { ICAFDecayableItems__factory } from "./ICAFDecayableItems__factory";
export { ICAFEventItems__factory } from "./ICAFEventItems__factory";
export { ICAFGameEconomy__factory } from "./ICAFGameEconomy__factory";
export { ICAFGameManager__factory } from "./ICAFGameManager__factory";
export { ICAFItems__factory } from "./ICAFItems__factory";
export { ICAFItemsManager__factory } from "./ICAFItemsManager__factory";
export { ICAFManufacturableItems__factory } from "./ICAFManufacturableItems__factory";
export { ICAFMaterialFactory__factory } from "./ICAFMaterialFactory__factory";
export { ICAFProductItems__factory } from "./ICAFProductItems__factory";
