/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICAFResaleStore,
  ICAFResaleStoreInterface,
} from "../../../contracts/marketplace/ICAFResaleStore";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_itemId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
    ],
    name: "ItemResold",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_itemId",
        type: "uint256",
      },
    ],
    name: "calculateResalePrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_itemId",
        type: "uint256",
      },
    ],
    name: "resell",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICAFResaleStore__factory {
  static readonly abi = _abi;
  static createInterface(): ICAFResaleStoreInterface {
    return new Interface(_abi) as ICAFResaleStoreInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICAFResaleStore {
    return new Contract(address, _abi, runner) as unknown as ICAFResaleStore;
  }
}
