/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ICAFMaterialFactoryInterface extends Interface {
  getFunction(nameOrSignature: "produceProducts"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProductsProduced"): EventFragment;

  encodeFunctionData(
    functionFragment: "produceProducts",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "produceProducts",
    data: BytesLike
  ): Result;
}

export namespace ProductsProducedEvent {
  export type InputTuple = [
    _productType: BigNumberish,
    _rateProducedPerHour: BigNumberish
  ];
  export type OutputTuple = [
    _productType: bigint,
    _rateProducedPerHour: bigint
  ];
  export interface OutputObject {
    _productType: bigint;
    _rateProducedPerHour: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ICAFMaterialFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ICAFMaterialFactory;
  waitForDeployment(): Promise<this>;

  interface: ICAFMaterialFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  produceProducts: TypedContractMethod<
    [_productType: BigNumberish, _rateProducedPerHour: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "produceProducts"
  ): TypedContractMethod<
    [_productType: BigNumberish, _rateProducedPerHour: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ProductsProduced"
  ): TypedContractEvent<
    ProductsProducedEvent.InputTuple,
    ProductsProducedEvent.OutputTuple,
    ProductsProducedEvent.OutputObject
  >;

  filters: {
    "ProductsProduced(uint8,uint256)": TypedContractEvent<
      ProductsProducedEvent.InputTuple,
      ProductsProducedEvent.OutputTuple,
      ProductsProducedEvent.OutputObject
    >;
    ProductsProduced: TypedContractEvent<
      ProductsProducedEvent.InputTuple,
      ProductsProducedEvent.OutputTuple,
      ProductsProducedEvent.OutputObject
    >;
  };
}
