/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICAFCompanyItems } from "./ICAFCompanyItems";
export type { ICAFContractRegistry } from "./ICAFContractRegistry";
export type { ICAFDecayableItems } from "./ICAFDecayableItems";
export type { ICAFEventItems } from "./ICAFEventItems";
export type { ICAFGameEconomy } from "./ICAFGameEconomy";
export type { ICAFGameManager } from "./ICAFGameManager";
export type { ICAFItems } from "./ICAFItems";
export type { ICAFItemsManager } from "./ICAFItemsManager";
export type { ICAFManufacturableItems } from "./ICAFManufacturableItems";
export type { ICAFMaterialFactory } from "./ICAFMaterialFactory";
export type { ICAFProductItems } from "./ICAFProductItems";
