/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "ERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155__factory>;
    getContractFactory(
      name: "IERC1155MetadataURI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155MetadataURI__factory>;
    getContractFactory(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155__factory>;
    getContractFactory(
      name: "IERC1155Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Receiver__factory>;
    getContractFactory(
      name: "ERC1155Holder",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155Holder__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeCast__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "Strings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Strings__factory>;
    getContractFactory(
      name: "CAFAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CAFAccessControl__factory>;
    getContractFactory(
      name: "CAFContractRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CAFContractRegistry__factory>;
    getContractFactory(
      name: "CAFGameEconomy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CAFGameEconomy__factory>;
    getContractFactory(
      name: "CAFGameManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CAFGameManager__factory>;
    getContractFactory(
      name: "CAFModuleBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CAFModuleBase__factory>;
    getContractFactory(
      name: "ICAFCompanyItems",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAFCompanyItems__factory>;
    getContractFactory(
      name: "ICAFContractRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAFContractRegistry__factory>;
    getContractFactory(
      name: "ICAFDecayableItems",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAFDecayableItems__factory>;
    getContractFactory(
      name: "ICAFEventItems",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAFEventItems__factory>;
    getContractFactory(
      name: "ICAFGameEconomy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAFGameEconomy__factory>;
    getContractFactory(
      name: "ICAFGameManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAFGameManager__factory>;
    getContractFactory(
      name: "ICAFItems",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAFItems__factory>;
    getContractFactory(
      name: "ICAFItemsManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAFItemsManager__factory>;
    getContractFactory(
      name: "ICAFManufacturableItems",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAFManufacturableItems__factory>;
    getContractFactory(
      name: "ICAFMaterialFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAFMaterialFactory__factory>;
    getContractFactory(
      name: "ICAFProductItems",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAFProductItems__factory>;
    getContractFactory(
      name: "CAFItemsManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CAFItemsManager__factory>;
    getContractFactory(
      name: "ControlLibrary",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ControlLibrary__factory>;
    getContractFactory(
      name: "ICAFToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAFToken__factory>;
    getContractFactory(
      name: "CAFMarketplace",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CAFMarketplace__factory>;
    getContractFactory(
      name: "ICAFMarketplace",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAFMarketplace__factory>;
    getContractFactory(
      name: "ICAFResaleStore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICAFResaleStore__factory>;
    getContractFactory(
      name: "CAFToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CAFToken__factory>;

    getContractAt(
      name: "AccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "IAccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "ERC1155",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155>;
    getContractAt(
      name: "IERC1155MetadataURI",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155MetadataURI>;
    getContractAt(
      name: "IERC1155",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155>;
    getContractAt(
      name: "IERC1155Receiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Receiver>;
    getContractAt(
      name: "ERC1155Holder",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155Holder>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "SafeCast",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeCast>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "Strings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Strings>;
    getContractAt(
      name: "CAFAccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CAFAccessControl>;
    getContractAt(
      name: "CAFContractRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CAFContractRegistry>;
    getContractAt(
      name: "CAFGameEconomy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CAFGameEconomy>;
    getContractAt(
      name: "CAFGameManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CAFGameManager>;
    getContractAt(
      name: "CAFModuleBase",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CAFModuleBase>;
    getContractAt(
      name: "ICAFCompanyItems",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAFCompanyItems>;
    getContractAt(
      name: "ICAFContractRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAFContractRegistry>;
    getContractAt(
      name: "ICAFDecayableItems",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAFDecayableItems>;
    getContractAt(
      name: "ICAFEventItems",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAFEventItems>;
    getContractAt(
      name: "ICAFGameEconomy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAFGameEconomy>;
    getContractAt(
      name: "ICAFGameManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAFGameManager>;
    getContractAt(
      name: "ICAFItems",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAFItems>;
    getContractAt(
      name: "ICAFItemsManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAFItemsManager>;
    getContractAt(
      name: "ICAFManufacturableItems",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAFManufacturableItems>;
    getContractAt(
      name: "ICAFMaterialFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAFMaterialFactory>;
    getContractAt(
      name: "ICAFProductItems",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAFProductItems>;
    getContractAt(
      name: "CAFItemsManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CAFItemsManager>;
    getContractAt(
      name: "ControlLibrary",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ControlLibrary>;
    getContractAt(
      name: "ICAFToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAFToken>;
    getContractAt(
      name: "CAFMarketplace",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CAFMarketplace>;
    getContractAt(
      name: "ICAFMarketplace",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAFMarketplace>;
    getContractAt(
      name: "ICAFResaleStore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICAFResaleStore>;
    getContractAt(
      name: "CAFToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CAFToken>;

    deployContract(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC1155",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1155>;
    deployContract(
      name: "IERC1155MetadataURI",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155MetadataURI>;
    deployContract(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155>;
    deployContract(
      name: "IERC1155Receiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Receiver>;
    deployContract(
      name: "ERC1155Holder",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1155Holder>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "Strings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "CAFAccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFAccessControl>;
    deployContract(
      name: "CAFContractRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFContractRegistry>;
    deployContract(
      name: "CAFGameEconomy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFGameEconomy>;
    deployContract(
      name: "CAFGameManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFGameManager>;
    deployContract(
      name: "CAFModuleBase",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFModuleBase>;
    deployContract(
      name: "ICAFCompanyItems",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFCompanyItems>;
    deployContract(
      name: "ICAFContractRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFContractRegistry>;
    deployContract(
      name: "ICAFDecayableItems",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFDecayableItems>;
    deployContract(
      name: "ICAFEventItems",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFEventItems>;
    deployContract(
      name: "ICAFGameEconomy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFGameEconomy>;
    deployContract(
      name: "ICAFGameManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFGameManager>;
    deployContract(
      name: "ICAFItems",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFItems>;
    deployContract(
      name: "ICAFItemsManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFItemsManager>;
    deployContract(
      name: "ICAFManufacturableItems",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFManufacturableItems>;
    deployContract(
      name: "ICAFMaterialFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFMaterialFactory>;
    deployContract(
      name: "ICAFProductItems",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFProductItems>;
    deployContract(
      name: "CAFItemsManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFItemsManager>;
    deployContract(
      name: "ControlLibrary",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ControlLibrary>;
    deployContract(
      name: "ICAFToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFToken>;
    deployContract(
      name: "CAFMarketplace",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFMarketplace>;
    deployContract(
      name: "ICAFMarketplace",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFMarketplace>;
    deployContract(
      name: "ICAFResaleStore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFResaleStore>;
    deployContract(
      name: "CAFToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFToken>;

    deployContract(
      name: "AccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "IAccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC1155",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1155>;
    deployContract(
      name: "IERC1155MetadataURI",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155MetadataURI>;
    deployContract(
      name: "IERC1155",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155>;
    deployContract(
      name: "IERC1155Receiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Receiver>;
    deployContract(
      name: "ERC1155Holder",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1155Holder>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "ReentrancyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "Strings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "CAFAccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFAccessControl>;
    deployContract(
      name: "CAFContractRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFContractRegistry>;
    deployContract(
      name: "CAFGameEconomy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFGameEconomy>;
    deployContract(
      name: "CAFGameManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFGameManager>;
    deployContract(
      name: "CAFModuleBase",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFModuleBase>;
    deployContract(
      name: "ICAFCompanyItems",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFCompanyItems>;
    deployContract(
      name: "ICAFContractRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFContractRegistry>;
    deployContract(
      name: "ICAFDecayableItems",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFDecayableItems>;
    deployContract(
      name: "ICAFEventItems",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFEventItems>;
    deployContract(
      name: "ICAFGameEconomy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFGameEconomy>;
    deployContract(
      name: "ICAFGameManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFGameManager>;
    deployContract(
      name: "ICAFItems",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFItems>;
    deployContract(
      name: "ICAFItemsManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFItemsManager>;
    deployContract(
      name: "ICAFManufacturableItems",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFManufacturableItems>;
    deployContract(
      name: "ICAFMaterialFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFMaterialFactory>;
    deployContract(
      name: "ICAFProductItems",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFProductItems>;
    deployContract(
      name: "CAFItemsManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFItemsManager>;
    deployContract(
      name: "ControlLibrary",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ControlLibrary>;
    deployContract(
      name: "ICAFToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFToken>;
    deployContract(
      name: "CAFMarketplace",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFMarketplace>;
    deployContract(
      name: "ICAFMarketplace",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFMarketplace>;
    deployContract(
      name: "ICAFResaleStore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICAFResaleStore>;
    deployContract(
      name: "CAFToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CAFToken>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
