/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CAFAccessControl } from "./CAFAccessControl";
export type { CAFContractRegistry } from "./CAFContractRegistry";
export type { CAFGameEconomy } from "./CAFGameEconomy";
export type { CAFGameManager } from "./CAFGameManager";
export type { CAFModuleBase } from "./CAFModuleBase";
