import { Address } from "viem"
export default {
    contracts: {
        CAF_CONTRACT_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_CAF_CONTRACT_REGISTRY_CONTRACT_ADDRESS as Address,
        CAF_GAME_MANAGER_ADDRESS: process.env.NEXT_PUBLIC_CAF_GAME_MANAGER_CONTRACT_ADDRESS as Address,
        CAF_MARKETPLACE_ADDRESS: process.env.NEXT_PUBLIC_CAF_MARKETPLACE_CONTRACT_ADDRESS as Address,
        CAF_GAME_ECONOMY_ADDRESS: process.env.NEXT_PUBLIC_CAF_GAME_ECONOMY_CONTRACT_ADDRESS as Address,
        CAF_ITEMS_MANAGER_ADDRESS: process.env.NEXT_PUBLIC_CAF_ITEMS_MANAGER_CONTRACT_ADDRESS as Address,
        CAF_TOKEN_ADDRESS: process.env.NEXT_PUBLIC_CAF_TOKEN_CONTRACT_ADDRESS as Address
    },
    walletconnet: {
        PROJECT_ID: process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID as string,
    },
}