export default {
    contracts: {
        CAF_TOKEN_ADDRESS: process.env.NEXT_PUBLIC_CAF_TOKEN_ADDRESS as string,
        CAF_CONTRACT_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_CAF_CONTRACT_REGISTRY_ADDRESS as string,
        CAF_GAME_MANAGER_ADDRESS: process.env.NEXT_PUBLIC_CAF_GAME_MANAGER_ADDRESS as string,
        CAF_GAME_ECONOMY_ADDRESS: process.env.NEXT_PUBLIC_CAF_GAME_ECONOMY_ADDRESS as string,
        CAF_PRODUCT_ITEMS_ADDRESS: process.env.NEXT_PUBLIC_CAF_PRODUCT_ITEMS_ADDRESS as string,
        CAF_COMPANY_ITEMS_ADDRESS: process.env.NEXT_PUBLIC_CAF_COMPANY_ITEMS_ADDRESS as string,
        CAF_EVENT_ITEMS_ADDRESS: process.env.NEXT_PUBLIC_CAF_EVENT_ITEMS_ADDRESS as string,
        CAF_MATERIAL_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_CAF_MATERIAL_FACTORY_ADDRESS as string,
        CAF_MARKETPLACE_ADDRESS: process.env.NEXT_PUBLIC_CAF_MARKETPLACE_ADDRESS as string,
        CAF_POOL_FACTORY_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_CAF_POOL_FACTORY_CONTRACT_ADDRESS as string
    },
    walletconnet: {
        PROJECT_ID: process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID as string,
    },
}